# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget vtkh_lodepng vtkh_utils vtkh_core vtkh_filters vtkh_rendering vtkh_compositing vtkh)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target vtkh_lodepng
add_library(vtkh_lodepng STATIC IMPORTED)

# Create imported target vtkh_utils
add_library(vtkh_utils STATIC IMPORTED)

set_target_properties(vtkh_utils PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_cont;vtkm_filter;vtkm_rendering;vtkh_lodepng"
)

# Create imported target vtkh_core
add_library(vtkh_core STATIC IMPORTED)

set_target_properties(vtkh_core PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_cont;vtkm_filter;vtkm_rendering;vtkh_utils"
)

# Create imported target vtkh_filters
add_library(vtkh_filters STATIC IMPORTED)

set_target_properties(vtkh_filters PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/A_Visit/GIT/visit-deps/windowsbuild/MSVC2017/vtkm/v1.7.0/include/vtkm-1.7;C:/A_Visit/GIT/visit-deps/windowsbuild/MSVC2017/vtkm/v1.7.0/include/vtkm-1.7/vtkm/thirdparty/diy"
  INTERFACE_LINK_LIBRARIES "vtkh_core;vtkh_utils;vtkm_compiler_flags;vtkm_diy"
)

# Create imported target vtkh_rendering
add_library(vtkh_rendering STATIC IMPORTED)

set_target_properties(vtkh_rendering PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkh_core;vtkh_utils;vtkh_filters;vtkh_compositing"
)

# Create imported target vtkh_compositing
add_library(vtkh_compositing STATIC IMPORTED)

set_target_properties(vtkh_compositing PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkh_core;vtkh_utils"
)

# Create imported target vtkh
add_library(vtkh INTERFACE IMPORTED)

set_target_properties(vtkh PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkh_core;vtkh_utils;vtkh_filters;vtkh_rendering"
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/VTKhTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
