QT.linguist_private.VERSION = 6.4.2
QT.linguist_private.name = QtLinguist
QT.linguist_private.module =
QT.linguist_private.libs = $$QT_MODULE_LIB_BASE
QT.linguist_private.includes = 
QT.linguist_private.frameworks = 
QT.linguist_private.depends = 
QT.linguist_private.uses = 
QT.linguist_private.module_config = v2 internal_module
QT.linguist_private.enabled_features = 
QT.linguist_private.disabled_features = 
