# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.22)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS vtkm_vectorization_flags vtkm_compiler_flags vtkm_developer_flags vtkmdiympi_nompi vtkmdiy diy_developer_flags vtkm_diy vtkm_lodepng vtkm_loguru vtkm_optionparser vtkm_lcl vtkm_cont vtkm_worklet vtkm_filter_core vtkm_filter vtkm_filter_clean_grid vtkm_filter_connected_components vtkm_filter_contour vtkm_filter_density_estimate vtkm_filter_entity_extraction vtkm_filter_flow vtkm_filter_image_processing vtkm_filter_field_conversion vtkm_filter_field_transform vtkm_filter_geometry_refinement vtkm_filter_mesh_info vtkm_filter_multi_block vtkm_filter_resampling vtkm_filter_scalar_topology vtkm_filter_vector_analysis vtkm_filter_zfp vtkm_rendering vtkm_rendering_gl_context vtkm_io vtkm_source)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target vtkm_vectorization_flags
add_library(vtkm_vectorization_flags INTERFACE IMPORTED)

# Create imported target vtkm_compiler_flags
add_library(vtkm_compiler_flags INTERFACE IMPORTED)

set_target_properties(vtkm_compiler_flags PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_COMPILE_OPTIONS "\$<\$<COMPILE_LANGUAGE:CXX>:/Gy>;\$<\$<COMPILE_LANGUAGE:CXX>:/bigobj>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtkm-1.9"
)

# Create imported target vtkm_developer_flags
add_library(vtkm_developer_flags INTERFACE IMPORTED)

set_target_properties(vtkm_developer_flags PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "_SCL_SECURE_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS"
  INTERFACE_COMPILE_OPTIONS "\$<\$<COMPILE_LANGUAGE:CXX>:-W3;-wd4702;-wd4505>"
)

# Create imported target vtkmdiympi_nompi
add_library(vtkmdiympi_nompi STATIC IMPORTED)

set_target_properties(vtkmdiympi_nompi PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:diy_developer_flags>"
)

# Create imported target vtkmdiy
add_library(vtkmdiy INTERFACE IMPORTED)

set_target_properties(vtkmdiy PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "VTKMDIY_NO_THREADS;VTKMDIY_MPI_AS_LIB;VTKMDIY_MPI_STATIC_BUILD"
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtkm-1.9/vtkm/thirdparty/diy/vtkmdiy/include;${_IMPORT_PREFIX}/include/vtkm-1.9/vtkm/thirdparty/diy/vtkmdiy/include/vtkmdiy/mpi"
  INTERFACE_LINK_LIBRARIES "vtkmdiympi_nompi"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "include/vtkm-1.9/vtkm/thirdparty/diy/vtkmdiy/include;include/vtkm-1.9/vtkm/thirdparty/diy/vtkmdiy/include/vtkmdiy/mpi"
)

# Create imported target diy_developer_flags
add_library(diy_developer_flags INTERFACE IMPORTED)

set_target_properties(diy_developer_flags PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "_SCL_SECURE_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS"
  INTERFACE_COMPILE_OPTIONS "\$<\$<COMPILE_LANGUAGE:CXX>:-W3>"
)

# Create imported target vtkm_diy
add_library(vtkm_diy INTERFACE IMPORTED)

set_target_properties(vtkm_diy PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtkm-1.9/vtkm/thirdparty/diy"
  INTERFACE_LINK_LIBRARIES "vtkmdiy;vtkmdiympi_nompi"
)

# Create imported target vtkm_lodepng
add_library(vtkm_lodepng INTERFACE IMPORTED)

# Create imported target vtkm_loguru
add_library(vtkm_loguru INTERFACE IMPORTED)

set_target_properties(vtkm_loguru PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtkm-1.9/vtkm/thirdparty/loguru"
  INTERFACE_LINK_LIBRARIES "Threads::Threads"
)

# Create imported target vtkm_optionparser
add_library(vtkm_optionparser INTERFACE IMPORTED)

set_target_properties(vtkm_optionparser PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtkm-1.9/vtkm/thirdparty/optionparser"
)

# Create imported target vtkm_lcl
add_library(vtkm_lcl INTERFACE IMPORTED)

set_target_properties(vtkm_lcl PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/vtkm-1.9/vtkm/thirdparty/lcl/vtkmlcl"
)

# Create imported target vtkm_cont
add_library(vtkm_cont STATIC IMPORTED)

set_target_properties(vtkm_cont PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_compiler_flags;Threads::Threads;vtkm_optionparser;vtkm_diy;vtkm_lcl;\$<LINK_ONLY:vtkm_loguru>"
)

# Create imported target vtkm_worklet
add_library(vtkm_worklet STATIC IMPORTED)

set_target_properties(vtkm_worklet PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_cont"
)

# Create imported target vtkm_filter_core
add_library(vtkm_filter_core STATIC IMPORTED)

set_target_properties(vtkm_filter_core PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_cont;vtkm_worklet"
)

# Create imported target vtkm_filter
add_library(vtkm_filter INTERFACE IMPORTED)

set_target_properties(vtkm_filter PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_filter_core;vtkm_filter_clean_grid;vtkm_filter_connected_components;vtkm_filter_contour;vtkm_filter_density_estimate;vtkm_filter_entity_extraction;vtkm_filter_flow;vtkm_filter_image_processing;vtkm_filter_field_conversion;vtkm_filter_field_transform;vtkm_filter_geometry_refinement;vtkm_filter_mesh_info;vtkm_filter_multi_block;vtkm_filter_resampling;vtkm_filter_scalar_topology;vtkm_filter_vector_analysis;vtkm_filter_zfp"
)

# Create imported target vtkm_filter_clean_grid
add_library(vtkm_filter_clean_grid STATIC IMPORTED)

set_target_properties(vtkm_filter_clean_grid PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:vtkm_worklet>;vtkm_filter_core"
)

# Create imported target vtkm_filter_connected_components
add_library(vtkm_filter_connected_components STATIC IMPORTED)

set_target_properties(vtkm_filter_connected_components PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:vtkm_worklet>;vtkm_filter_core"
)

# Create imported target vtkm_filter_contour
add_library(vtkm_filter_contour STATIC IMPORTED)

set_target_properties(vtkm_filter_contour PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:vtkm_worklet>;vtkm_filter_core;vtkm_filter_vector_analysis;vtkm_filter_mesh_info"
)

# Create imported target vtkm_filter_density_estimate
add_library(vtkm_filter_density_estimate STATIC IMPORTED)

set_target_properties(vtkm_filter_density_estimate PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:vtkm_worklet>;vtkm_filter_core"
)

# Create imported target vtkm_filter_entity_extraction
add_library(vtkm_filter_entity_extraction STATIC IMPORTED)

set_target_properties(vtkm_filter_entity_extraction PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:vtkm_worklet>;\$<LINK_ONLY:vtkm_filter_clean_grid>;vtkm_filter_core"
)

# Create imported target vtkm_filter_flow
add_library(vtkm_filter_flow STATIC IMPORTED)

set_target_properties(vtkm_filter_flow PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_worklet;vtkm_filter_core"
)

# Create imported target vtkm_filter_image_processing
add_library(vtkm_filter_image_processing STATIC IMPORTED)

set_target_properties(vtkm_filter_image_processing PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_worklet;vtkm_filter_core"
)

# Create imported target vtkm_filter_field_conversion
add_library(vtkm_filter_field_conversion STATIC IMPORTED)

set_target_properties(vtkm_filter_field_conversion PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_worklet;vtkm_filter_core"
)

# Create imported target vtkm_filter_field_transform
add_library(vtkm_filter_field_transform STATIC IMPORTED)

set_target_properties(vtkm_filter_field_transform PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_worklet;vtkm_filter_core"
)

# Create imported target vtkm_filter_geometry_refinement
add_library(vtkm_filter_geometry_refinement STATIC IMPORTED)

set_target_properties(vtkm_filter_geometry_refinement PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_worklet;vtkm_filter_core"
)

# Create imported target vtkm_filter_mesh_info
add_library(vtkm_filter_mesh_info STATIC IMPORTED)

set_target_properties(vtkm_filter_mesh_info PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_worklet;vtkm_filter_core"
)

# Create imported target vtkm_filter_multi_block
add_library(vtkm_filter_multi_block STATIC IMPORTED)

set_target_properties(vtkm_filter_multi_block PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_worklet;vtkm_filter_core"
)

# Create imported target vtkm_filter_resampling
add_library(vtkm_filter_resampling STATIC IMPORTED)

set_target_properties(vtkm_filter_resampling PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_worklet;vtkm_filter_core"
)

# Create imported target vtkm_filter_scalar_topology
add_library(vtkm_filter_scalar_topology STATIC IMPORTED)

set_target_properties(vtkm_filter_scalar_topology PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_worklet;vtkm_filter_core"
)

# Create imported target vtkm_filter_vector_analysis
add_library(vtkm_filter_vector_analysis STATIC IMPORTED)

set_target_properties(vtkm_filter_vector_analysis PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_worklet;vtkm_filter_core"
)

# Create imported target vtkm_filter_zfp
add_library(vtkm_filter_zfp STATIC IMPORTED)

set_target_properties(vtkm_filter_zfp PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_worklet;vtkm_filter_core"
)

# Create imported target vtkm_rendering
add_library(vtkm_rendering STATIC IMPORTED)

set_target_properties(vtkm_rendering PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_filter_image_processing;vtkm_filter_entity_extraction;vtkm_io;vtkm_rendering_gl_context"
)

# Create imported target vtkm_rendering_gl_context
add_library(vtkm_rendering_gl_context INTERFACE IMPORTED)

# Create imported target vtkm_io
add_library(vtkm_io STATIC IMPORTED)

set_target_properties(vtkm_io PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_cont;\$<LINK_ONLY:vtkm_lodepng>"
)

# Create imported target vtkm_source
add_library(vtkm_source STATIC IMPORTED)

set_target_properties(vtkm_source PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkm_cont;vtkm_filter_field_conversion;vtkm_filter_multi_block"
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/VTKmTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
