set(vtkPython_LOADED 1)
set(vtkPython_DEPENDS "vtkCommonCore")
set(vtkPython_LIBRARIES "C:/A_Visit/ForRegression/visit-deps/windowsbuild/MSVC2017/python/3.7.7/libs/python37.lib")
set(vtkPython_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-8.1;C:/A_Visit/ForRegression/visit-deps/windowsbuild/MSVC2017/python/3.7.7/include")
set(vtkPython_LIBRARY_DIRS "")
set(vtkPython_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkPython_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkPythonHierarchy.txt")
set(vtkPython_KIT "")
set(vtkPython_TARGETS_FILE "")
set(vtkPython_EXCLUDE_FROM_WRAPPING 1)
set(VTK_PYTHONPATH "C:/A_VisIt/ForRegression/visit-deps/windowsbuild/MSVC2017/vtk/8.1.0/lib/python3.7/site-packages")

