set(vtkPython_LOADED 1)
set(vtkPython_DEPENDS "vtkCommonCore")
set(vtkPython_LIBRARIES "${PYTHON_LIBRARY}")
set(vtkPython_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-8.1;${PYTHON_INCLUDE_DIR}")
set(vtkPython_LIBRARY_DIRS "")
set(vtkPython_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkPython_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkPythonHierarchy.txt")
set(vtkPython_KIT "")
set(vtkPython_TARGETS_FILE "")
set(vtkPython_EXCLUDE_FROM_WRAPPING 1)
set(VTK_PYTHONPATH "${VTK_INSTALL_PREFIX}/lib/python2.7/site-packages")

