
#ifndef VTKWRAPPINGPYTHONCORE_EXPORT_H
#define VTKWRAPPINGPYTHONCORE_EXPORT_H

#ifdef VTKWRAPPINGPYTHONCORE_STATIC_DEFINE
#  define VTKWRAPPINGPYTHONCORE_EXPORT
#  define VTKWRAPPINGPYTHONCORE_NO_EXPORT
#else
#  ifndef VTKWRAPPINGPYTHONCORE_EXPORT
#    ifdef WrappingPythonCore_EXPORTS
        /* We are building this library */
#      define VTKWRAPPINGPYTHONCORE_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKWRAPPINGPYTHONCORE_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKWRAPPINGPYTHONCORE_NO_EXPORT
#    define VTKWRAPPINGPYTHONCORE_NO_EXPORT 
#  endif
#endif

#ifndef VTKWRAPPINGPYTHONCORE_DEPRECATED
#  define VTKWRAPPINGPYTHONCORE_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKWRAPPINGPYTHONCORE_DEPRECATED_EXPORT
#  define VTKWRAPPINGPYTHONCORE_DEPRECATED_EXPORT VTKWRAPPINGPYTHONCORE_EXPORT VTKWRAPPINGPYTHONCORE_DEPRECATED
#endif

#ifndef VTKWRAPPINGPYTHONCORE_DEPRECATED_NO_EXPORT
#  define VTKWRAPPINGPYTHONCORE_DEPRECATED_NO_EXPORT VTKWRAPPINGPYTHONCORE_NO_EXPORT VTKWRAPPINGPYTHONCORE_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKWRAPPINGPYTHONCORE_NO_DEPRECATED
#    define VTKWRAPPINGPYTHONCORE_NO_DEPRECATED
#  endif
#endif

#endif /* VTKWRAPPINGPYTHONCORE_EXPORT_H */
