/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the raycastervs string.
 *
 */
#ifndef raycastervs_h
#define raycastervs_h

#include "vtkRenderingVolumeOpenGL2Module.h"

VTKRENDERINGVOLUMEOPENGL2_EXPORT extern const char *raycastervs;

#endif /* #ifndef raycastervs_h */
