/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the raycasterfs string.
 *
 */
#ifndef raycasterfs_h
#define raycasterfs_h

#include "vtkRenderingVolumeOpenGL2Module.h"

VTKRENDERINGVOLUMEOPENGL2_EXPORT extern const char *raycasterfs;

#endif /* #ifndef raycasterfs_h */
