/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the vtkDepthPeelingPassFinalFS string.
 *
 */
#ifndef vtkDepthPeelingPassFinalFS_h
#define vtkDepthPeelingPassFinalFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkDepthPeelingPassFinalFS;

#endif /* #ifndef vtkDepthPeelingPassFinalFS_h */
