/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the vtkDepthPeelingPassIntermediateFS string.
 *
 */
#ifndef vtkDepthPeelingPassIntermediateFS_h
#define vtkDepthPeelingPassIntermediateFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkDepthPeelingPassIntermediateFS;

#endif /* #ifndef vtkDepthPeelingPassIntermediateFS_h */
