/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the vtkEDLComposeFS string.
 *
 */
#ifndef vtkEDLComposeFS_h
#define vtkEDLComposeFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkEDLComposeFS;

#endif /* #ifndef vtkEDLComposeFS_h */
