/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the vtkEDLBilateralFilterFS string.
 *
 */
#ifndef vtkEDLBilateralFilterFS_h
#define vtkEDLBilateralFilterFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkEDLBilateralFilterFS;

#endif /* #ifndef vtkEDLBilateralFilterFS_h */
