/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the vtkGlyph3DVS string.
 *
 */
#ifndef vtkGlyph3DVS_h
#define vtkGlyph3DVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkGlyph3DVS;

#endif /* #ifndef vtkGlyph3DVS_h */
