/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the vtkglProjectedTetrahedraVS string.
 *
 */
#ifndef vtkglProjectedTetrahedraVS_h
#define vtkglProjectedTetrahedraVS_h

#include "vtkRenderingVolumeOpenGL2Module.h"

VTKRENDERINGVOLUMEOPENGL2_EXPORT extern const char *vtkglProjectedTetrahedraVS;

#endif /* #ifndef vtkglProjectedTetrahedraVS_h */
