/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the vtkGaussianBlurPassVS string.
 *
 */
#ifndef vtkGaussianBlurPassVS_h
#define vtkGaussianBlurPassVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkGaussianBlurPassVS;

#endif /* #ifndef vtkGaussianBlurPassVS_h */
