/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the vtkGaussianBlurPassFS string.
 *
 */
#ifndef vtkGaussianBlurPassFS_h
#define vtkGaussianBlurPassFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkGaussianBlurPassFS;

#endif /* #ifndef vtkGaussianBlurPassFS_h */
