/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the vtkPointFillPassFS string.
 *
 */
#ifndef vtkPointFillPassFS_h
#define vtkPointFillPassFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkPointFillPassFS;

#endif /* #ifndef vtkPointFillPassFS_h */
