/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the vtkPolyData2DVS string.
 *
 */
#ifndef vtkPolyData2DVS_h
#define vtkPolyData2DVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkPolyData2DVS;

#endif /* #ifndef vtkPolyData2DVS_h */
