/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the vtkPolyDataWideLineGS string.
 *
 */
#ifndef vtkPolyDataWideLineGS_h
#define vtkPolyDataWideLineGS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkPolyDataWideLineGS;

#endif /* #ifndef vtkPolyDataWideLineGS_h */
