/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the vtkPolyDataVS string.
 *
 */
#ifndef vtkPolyDataVS_h
#define vtkPolyDataVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkPolyDataVS;

#endif /* #ifndef vtkPolyDataVS_h */
