/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the vtkSobelGradientMagnitudePass2FS string.
 *
 */
#ifndef vtkSobelGradientMagnitudePass2FS_h
#define vtkSobelGradientMagnitudePass2FS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkSobelGradientMagnitudePass2FS;

#endif /* #ifndef vtkSobelGradientMagnitudePass2FS_h */
