/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the vtkSimpleMotionBlurPassFS string.
 *
 */
#ifndef vtkSimpleMotionBlurPassFS_h
#define vtkSimpleMotionBlurPassFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkSimpleMotionBlurPassFS;

#endif /* #ifndef vtkSimpleMotionBlurPassFS_h */
