/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the vtkTextureObjectFS string.
 *
 */
#ifndef vtkTextureObjectFS_h
#define vtkTextureObjectFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkTextureObjectFS;

#endif /* #ifndef vtkTextureObjectFS_h */
