/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-8.1.exe
 * 
 * Declare the vtkTextureObjectVS string.
 *
 */
#ifndef vtkTextureObjectVS_h
#define vtkTextureObjectVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkTextureObjectVS;

#endif /* #ifndef vtkTextureObjectVS_h */
