# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget conduit conduit_python conduit_relay conduit_relay_python conduit_relay_io_python conduit_relay_web_python conduit_relay_mpi conduit_relay_mpi_io conduit_blueprint conduit_blueprint_python conduit_blueprint_mcarray_python conduit_blueprint_mcarray_examples_python conduit_blueprint_mesh_python conduit_blueprint_mesh_examples_python)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target conduit
add_library(conduit SHARED IMPORTED)

# Create imported target conduit_python
add_library(conduit_python MODULE IMPORTED)

set_target_properties(conduit_python PROPERTIES
  INTERFACE_LINK_LIBRARIES "python27.lib;conduit"
)

# Create imported target conduit_relay
add_library(conduit_relay SHARED IMPORTED)

set_target_properties(conduit_relay PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${HDF5_INCLUDE_DIR}include"
  INTERFACE_LINK_LIBRARIES "conduit;conduit_blueprint;hdf5;hdf5_cpp;hdf5_hl"
)

# Create imported target conduit_relay_python
add_library(conduit_relay_python MODULE IMPORTED)

set_target_properties(conduit_relay_python PROPERTIES
  INTERFACE_LINK_LIBRARIES "python27.lib;conduit;conduit_relay"
)

# Create imported target conduit_relay_io_python
add_library(conduit_relay_io_python MODULE IMPORTED)

set_target_properties(conduit_relay_io_python PROPERTIES
  INTERFACE_LINK_LIBRARIES "python27.lib;conduit;conduit_relay"
)

# Create imported target conduit_relay_web_python
add_library(conduit_relay_web_python MODULE IMPORTED)

set_target_properties(conduit_relay_web_python PROPERTIES
  INTERFACE_LINK_LIBRARIES "python27.lib;conduit;conduit_relay"
)

# Create imported target conduit_relay_mpi
add_library(conduit_relay_mpi SHARED IMPORTED)

set_target_properties(conduit_relay_mpi PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Program Files (x86)/Microsoft SDKs/MPI/Include;C:/Program Files (x86)/Microsoft SDKs/MPI/Include"
  INTERFACE_LINK_LIBRARIES "conduit;C:/Program Files (x86)/Microsoft SDKs/MPI/Lib/x64/msmpi.lib;C:/Program Files (x86)/Microsoft SDKs/MPI/Lib/x64/msmpi.lib"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "C:/Program Files (x86)/Microsoft SDKs/MPI/Include;C:/Program Files (x86)/Microsoft SDKs/MPI/Include"
)

# Create imported target conduit_relay_mpi_io
add_library(conduit_relay_mpi_io SHARED IMPORTED)

set_target_properties(conduit_relay_mpi_io PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-DCONDUIT_RELAY_IO_MPI_ENABLED"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Program Files (x86)/Microsoft SDKs/MPI/Include;${HDF5_INCLUDE_DIR}"
  INTERFACE_LINK_LIBRARIES "conduit;C:/Program Files (x86)/Microsoft SDKs/MPI/Lib/x64/msmpi.lib;hdf5;hdf5_cpp;hdf5_hl"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "C:/Program Files (x86)/Microsoft SDKs/MPI/Include"
)

# Create imported target conduit_blueprint
add_library(conduit_blueprint SHARED IMPORTED)

set_target_properties(conduit_blueprint PROPERTIES
  INTERFACE_LINK_LIBRARIES "conduit"
)

# Create imported target conduit_blueprint_python
add_library(conduit_blueprint_python MODULE IMPORTED)

set_target_properties(conduit_blueprint_python PROPERTIES
  INTERFACE_LINK_LIBRARIES "python27.lib;conduit;conduit_blueprint"
)

# Create imported target conduit_blueprint_mcarray_python
add_library(conduit_blueprint_mcarray_python MODULE IMPORTED)

set_target_properties(conduit_blueprint_mcarray_python PROPERTIES
  INTERFACE_LINK_LIBRARIES "python27.lib;conduit;conduit_blueprint"
)

# Create imported target conduit_blueprint_mcarray_examples_python
add_library(conduit_blueprint_mcarray_examples_python MODULE IMPORTED)

set_target_properties(conduit_blueprint_mcarray_examples_python PROPERTIES
  INTERFACE_LINK_LIBRARIES "python27.lib;conduit;conduit_blueprint"
)

# Create imported target conduit_blueprint_mesh_python
add_library(conduit_blueprint_mesh_python MODULE IMPORTED)

set_target_properties(conduit_blueprint_mesh_python PROPERTIES
  INTERFACE_LINK_LIBRARIES "python27.lib;conduit;conduit_blueprint"
)

# Create imported target conduit_blueprint_mesh_examples_python
add_library(conduit_blueprint_mesh_examples_python MODULE IMPORTED)

set_target_properties(conduit_blueprint_mesh_examples_python PROPERTIES
  INTERFACE_LINK_LIBRARIES "python27.lib;conduit;conduit_blueprint"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/conduit-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
